version: '3'

services:
  
  broker:
    container_name: broker
    build:
      context: ./
      dockerfile: Dockerfile-Broker
    depends_on:
      - mongo-broker
#    network_mode: host
    ports:
      - 8000:8000

  mongo-broker:
    image: mongo
    container_name: mongo-broker
#    network_mode: host
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE:"brokerdb"
      - MONGO_INITDB_ROOT_USERNAME:"admin"
      - MONGO_INITDB_ROOT_PASSWORD:"admin"
    volumes:
      # scripts de semeadura
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # volumes nomeados
      - "/var/lib/mongodb-broker:/data/db"
