FROM python:alpine3.7
MAINTAINER Necos

COPY src/ /src
WORKDIR src/

RUN apk add --update build-base libffi-dev openssl-dev python3-dev
RUN pip install --upgrade pip
RUN pip3 install -r requeriments.txt \ 
                    install hug -U

CMD ["hug", "-f", "slice_broker.py", "-p", "8000"]
