FROM ubuntu:18.04
MAINTAINER Necos

RUN apt-get update

#Instalacao bibliotecas
RUN apt-get install -y python3 python3-pip
RUN pip3 install hug -U 
RUN pip3 install requests grequests jsonlib-python3 objectpath pymongo pyyaml

COPY src/ /home/broker/src/

WORKDIR /home/broker/src/

EXPOSE 8000

CMD ["hug", "-f", "slice_broker.py", "-p", "8000"]
