-- MySQL Script generated by MySQL Workbench
-- ter 30 abr 2019 12:02:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dc_slice_controller
-- -----------------------------------------------------
USE dc_slice_controller;
-- -----------------------------------------------------
-- Table `VIM_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VIM_Type` ;

CREATE TABLE IF NOT EXISTS `VIM_Type` (
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VIM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VIM` ;

CREATE TABLE IF NOT EXISTS `VIM` (
  `uuid` VARCHAR(45) NOT NULL,
  `dashboard_user` VARCHAR(45) NULL,
  `dashboard_password` VARCHAR(45) NULL,
  `VIM_Type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_VIM_VIM_Type1_idx` (`VIM_Type_name` ASC),
  CONSTRAINT `fk_VIM_VIM_Type1`
    FOREIGN KEY (`VIM_Type_name`)
    REFERENCES `VIM_Type` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Controller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Controller` ;

CREATE TABLE IF NOT EXISTS `Controller` (
  `id` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NULL,
  `configuration_protocol` VARCHAR(45) NULL,
  `configuration_interface` VARCHAR(45) NULL,
  `provider` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Slice_Part`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Slice_Part` ;

CREATE TABLE IF NOT EXISTS `Slice_Part` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `valid_from` DATETIME NULL,
  `valid_until` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `port` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  `VIM_uuid` VARCHAR(45) NOT NULL,
  `Controller_id` VARCHAR(45) NOT NULL,
  `User_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `Controller_id`),
  INDEX `fk_Slice_VIM1_idx` (`VIM_uuid` ASC),
  INDEX `fk_Slice_Part_controller1_idx` (`Controller_id` ASC),
  INDEX `fk_Slice_Part_User1_idx` (`User_name` ASC),
  CONSTRAINT `fk_Slice_VIM1`
    FOREIGN KEY (`VIM_uuid`)
    REFERENCES `VIM` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Slice_Part_controller1`
    FOREIGN KEY (`Controller_id`)
    REFERENCES `Controller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Slice_Part_User1`
    FOREIGN KEY (`User_name`)
    REFERENCES `User` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Template` ;

CREATE TABLE IF NOT EXISTS `Template` (
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `version` VARCHAR(15) NOT NULL,
  `memory` INT NOT NULL,
  `vcpu` INT NOT NULL,
  `storage` INT NOT NULL,
  `ip_address` VARCHAR(15) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `VIM_Type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`, `version`),
  INDEX `fk_Template_VIM_Type1_idx` (`VIM_Type_name` ASC),
  CONSTRAINT `fk_Template_VIM_Type1`
    FOREIGN KEY (`VIM_Type_name`)
    REFERENCES `VIM_Type` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CPU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CPU` ;

CREATE TABLE IF NOT EXISTS `CPU` (
  `uuid` VARCHAR(45) NOT NULL,
  `cycles` INT NULL,
  `cores` INT NULL,
  `model` VARCHAR(45) NULL,
  `architecture` VARCHAR(45) NULL,
  `instruction_set` VARCHAR(45) NULL,
  PRIMARY KEY (`uuid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Host`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Host` ;

CREATE TABLE IF NOT EXISTS `Host` (
  `uuid` VARCHAR(45) NOT NULL,
  `memory` INT NOT NULL,
  `storage` INT NOT NULL,
  `ip_address` VARCHAR(15) NOT NULL,
  `hostname` VARCHAR(45) NULL,
  `availability` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `CPU_uuid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_Host_CPU1_idx` (`CPU_uuid` ASC),
  CONSTRAINT `fk_Host_CPU1`
    FOREIGN KEY (`CPU_uuid`)
    REFERENCES `CPU` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VM` ;

CREATE TABLE IF NOT EXISTS `VM` (
  `uuid` VARCHAR(45) NOT NULL,
  `name_yaml` VARCHAR(45) NOT NULL,
  `name_hypervisor` VARCHAR(150) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `memory` INT NOT NULL,
  `vcpu` INT NOT NULL,
  `storage` INT NOT NULL,
  `ip_address` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NULL,
  `Slice_Part_id` INT NOT NULL,
  `Host_uuid` VARCHAR(45) NOT NULL,
  `Template_name` VARCHAR(45) NOT NULL,
  `Template_version` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`uuid`),
  INDEX `fk_VM_Resource1_idx` (`Host_uuid` ASC),
  INDEX `fk_VM_Template1_idx` (`Template_name` ASC, `Template_version` ASC),
  INDEX `fk_VM_Slice_Part1_idx` (`Slice_Part_id` ASC),
  CONSTRAINT `fk_VM_Resource1`
    FOREIGN KEY (`Host_uuid`)
    REFERENCES `Host` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VM_Template1`
    FOREIGN KEY (`Template_name` , `Template_version`)
    REFERENCES `Template` (`name` , `version`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VM_Slice_Part1`
    FOREIGN KEY (`Slice_Part_id`)
    REFERENCES `Slice_Part` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
