version: '3'

services:
  
  agent:
    container_name: agent
    build:
      context: ./
      dockerfile: Dockerfile-Agent
    depends_on:
     - mongo-agent
    network_mode: host
    ports:
     - "8001:8001"

  mongo-agent:
    image: mongo
    container_name: mongo-agent
    network_mode: host
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE:"agentdb"
      - MONGO_INITDB_ROOT_USERNAME:"admin"
      - MONGO_INITDB_ROOT_PASSWORD:"admin"
    volumes:
#      - "/var/lib/mongodb-agent:/data/db"
      - "/home/gercom/lib/mongodb-agent:/data/db"

