FROM ubuntu:18.04
MAINTAINER Necos

RUN apt-get update

#Instalacao Bibliotecas
RUN apt-get install -y python3 python3-pip
RUN pip3 install hug -U 
RUN pip3 install requests grequests jsonlib-python3 objectpath pymongo pyyaml

COPY src/ /home/agent/src/

WORKDIR /home/agent/src/

CMD ["hug", "-f", "slice_agent.py", "-p", "8001"]
